### PR TITLE
fix,feat: Improve DebugActivity

### LINKED ISSUE #1140: When App Crashes, Debug Screen no longer shows with error
If my app crashes, Debug activity doesn't come up anymore so I don't know what the error message is. And I can't use logcat because I don't have root.

### PR DESCRIPTION
**Pull request by khaled-0**
fixes #1140 
DebugActivity now launched every time using intent because,
AlarmManager is unreliable

Also changed the crash message view from dialog to a bi directional scroll
Profit: formatted crash logs

Screenshot from 2024-06-01 13-32-45

### CODE REVIEW

File: app/src/main/assets/debug/SketchApplication.java [hunk 1]
```diff
@@ -20,33 +17,19 @@ public static Context getContext() {
...
-
-                    uncaughtExceptionHandler.uncaughtException(thread, throwable);
-                }
-            });
+                new Thread.UncaughtExceptionHandler() {
+                    @Override
+                    public void uncaughtException(Thread thread, Throwable throwable) {
+                        Intent intent = new Intent(getApplicationContext(), DebugActivity.class);
+                        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
+                        intent.putExtra("stacktrace", Log.getStackTraceString(throwable));
```
Comment (JavkhlanK) [inline app/src/main/assets/debug/SketchApplication.java:27]: This will break existing projects with a custom crash handler.

File: app/src/main/assets/debug/DebugActivity.java [hunk 2]
```diff
@@ -60,17 +64,21 @@ protected void onCreate(Bundle savedInstanceState) {
...
-                    }
-                })
-                .create();
-        dialog.show();
-        ((TextView) dialog.findViewById(android.R.id.message)).setTextIsSelectable(true);
+        setTitle(getTitle() + " Crashed");
+        setContentView(contentView(this, madeErrorMessage));
+    }
+
+    View contentView(Context context, String errorMessage) {
```
Comment (JavkhlanK) [inline app/src/main/assets/debug/DebugActivity.java:71]: Why a separate method? Why pass over `Context` in a non-static method?

**Review by JavkhlanK — CHANGES_REQUESTED** [review]

File: app/src/main/assets/debug/DebugActivity.java (hunk 2 above)
Comment (khaled-0) [reply app/src/main/assets/debug/DebugActivity.java:71]: ??? The method just returns the view, what's that got to do with non static

I put it in a method without any specific reason. just keeping the view buildings out of onCreate

File: app/src/main/assets/debug/SketchApplication.java (hunk 1 above)
Comment (khaled-0) [reply app/src/main/assets/debug/SketchApplication.java:27]: explain

Comment (JavkhlanK) [reply app/src/main/assets/debug/SketchApplication.java:27]: They rely on the extra being named `error`.

File: app/src/main/assets/debug/DebugActivity.java (hunk 2 above)
Comment (JavkhlanK) [reply app/src/main/assets/debug/DebugActivity.java:71]: It'd just be cleaner without an unnecessary extra method. The parameter is redundant too, since `this` can be used (it's not a static method).

**Comment by JavkhlanK** [comment]
Works great. What's suboptimal is that you can't easily take a screenshot of the entire stack trace anymore. I'm 100 % sure most users would not care and then start sending cut-off ones, making every helper's life harder. I think the horizontal scroll feature should be removed.

**Comment by khaled-0** [comment]
> Works great. What's suboptimal is that you can't easily take a screenshot of the entire stack trace anymore. I'm 100 % sure most users would not care and then start sending cut-off ones, making every helper's life harder. I think the horizontal scroll feature should be removed.

Or how about a copy button?

**Comment by JavkhlanK** [comment]
They'll probably still ignore that.

**Comment by khaled-0** [comment]
I dunno, go ahead and remove it then i guess

**Comment by guhg** [comment]
I think just adding a copy button above or below the error code with be good enough

**Comment by hasrat-ali** [comment]
Can't we just add inbuilt screenshot button?

**Comment by JavkhlanK** [comment]
> I think just adding a copy button above or below the error code with be good enough

There's a copy button in Sketchware Pro's crash screen. Not a lot of people used it afair. At least the messages weren't cut off in the dialog.

**Comment by PranavPurwar** [comment]
> > I think just adding a copy button above or below the error code with be good enough
> 
> There's a copy button in Sketchware Pro's crash screen. Not a lot of people used it afair. At least the messages weren't cut off in the dialog.

There isn't, yet.

**Comment by JavkhlanK** [comment]
wait maybe I misremembered lmao

**Comment by PranavPurwar** [comment]
yeah, it was never there so I made #1143
